-- Create New Event
insert into Events(
	EventCode,
    EventTitle,
	Durration,
	Deadline,
	EventPassword
)
Values
(
						-- $eventCode = base_convert((strval(time()) . sprintf('%05d',rand (0, 99999))), 10, 36);
	'1kxeqfw3ce',		-- event code generated by: systemtime appended by 5 digit random number, then converted into base 36
    'My First Event',	-- 55 char character limit
    7, 					-- this event takes 7 segments of time, (7*15)/60 = 1 hr 45 min
    '2020-11-23',		-- YYY-MM-DD
    'MyFakePassword'	-- 16 char character limit
)
;

insert into Users(
	UserID,				-- $userID = base_convert((strval(intval(time())-1600000000) . sprintf('%03d',rand (0, 999))), 10, 36);
	UserType,
	UserName,
    RSVP,
	Email,
	CalenderFile
)
Values
(
	'02rdds4d',
    
)
;

insert into  Days(
	EventCode,
	UserID,
	TimeArray,
	EventDate
)
Values
()
;
