-- Create New Event
SET @EventCode = '1kxeqfw3ce';
SET @UserID = 'e8l6kj91ek';
SET @InsertedDays = NULL;
insert into Events(
	EventCode,
    EventTitle,
	Duration,
	Deadline,
	EventPassword
)
Values
(
						-- $eventCode = base_convert((strval(time()) . sprintf('%05d',rand (0, 99999))), 10, 36);
	@EventCode,		-- event code generated by: systemtime appended by 5 digit random number, then converted into base 36
    'Friends Giving',	-- 55 char character limit
    11, 					-- this event takes 7 segments of time, (11*15)/60 = 2 hr 45 min
    '2020-11-23',		-- YYY-MM-DD
    'MyFakePassword'	-- 16 char character limit
)
;



insert into Users(
	UserID,				-- $userID = base_convert((strval(intval(time())-159999999) . sprintf('%03d',rand (0, 999)) . sprintf('%03d',rand (0, 999))) , 10, 36);
	UserType,			-- 'E' = Event
    RSVP,				-- True
	Email				-- Organizer's email
)
Values
(
	@UserID,
    'E', 
    True, 
    'organizer@email.me'
)
;

insert into  Days(
	EventCode,
	UserID,
	EventDate,
	TimeArray
)
Values
(
	@EventCode,
    @UserID, 
    '20201126',
    '000000000000000000000000000000000000000000000000111111111111111111111111111100000000000000000000'
),
(
	@EventCode,
    @UserID, 
    '20201127',
    '000000000000000000000000000000001111111111111111111111111111111111111111111111111111000000000000'
),
(
	@EventCode,
    @UserID, 
    '20201128',
    '000000000000000000000000000000000000111111111111111111111111111111110000000000000000000000000000'
)
;
Select Group_CONCAT(CONCAT(EventDate,': ',  IFNULL(TimeArray, 'NULL')) SEPARATOR '\r\n')
into @InsertedDays
From Days
Cross Join
	Users using(UserID)
Where 
		EventCode = @EventCode
    AND	UserType = 'E'
;

insert into LOGS(
	AssociatedUserID, 
    DateTime,
    Description
)
VALUES
(
	@UserID, 
    NOW(),
    'USER CREATED'
),
(
	@UserID, 
    NOW(),
    CONCAT('EVENT CREATED: ', @EventCode)
),
(
	@UserID, 
    NOW(),
    CONCAT_WS('\r\n','DAYS INSERTED for EVENT:',@EventCode, @InsertedDays)
);
SET @EventCode = NULL;
SET @UserID = NULL;
SET @InsertedDays = NULL;



SET @EventCode = '1kxeqfw3ce';
SET @UserID = 'e8l6kj91ek';
Set @UpdatedDay = '20201128';
Set @UpdatedTimeArray = '000000000011111111000000000000000000000000000111111111111111111111111111111110000000000000000000';
-- update Event: Change Existing day
update Days
Cross Join
	Users using(UserID)
SET
	TimeArray = @UpdatedTimeArray

WHERE
		EventCode = @EventCode
    AND	EventDate = @UpdatedDay
    AND	UserType = 'E'
;

insert into LOGS(
	AssociatedUserID, 
    DateTime,
    Description
)
VALUES
(
	@UserID , 
    NOW(),
    CONCAT_WS('\r\n','DAYS UPDATED for EVENT: ',@EventCode, CONCAT(@UpdatedDay,': ', @UpdatedTimeArray))
);
SET @EventCode = NULL;
SET @UserID = NULL;
Set @UpdatedDay = NULL;
Set @UpdatedTimeArray = NULL;

SELECT * FROM Days;

